version: '3.8'
services:
  can_i_deploy:
    image: pactfoundation/pact-cli:latest
    command: >
      pact-broker can-i-deploy 
      --pacticipant ${PACTICIPANT} 
      --version ${VERSION} 
      --to-environment production 
      --retry-while-unknown 6 
      --retry-interval 10
    volumes:
      - ./:/${PWD}
    environment:
      - PACT_BROKER_BASE_URL
      - PACT_BROKER_TOKEN
  record_deployment:
    image: pactfoundation/pact-cli:latest
    command: >
      pact-broker record_deployment 
      --pacticipant ${PACTICIPANT} 
      --version ${VERSION} 
      --environment production
    volumes:
      - ./:/${PWD}
    environment:
      - PACT_BROKER_BASE_URL
      - PACT_BROKER_TOKEN
  publish_provider_contract:
    image: pactfoundation/pact-cli:latest
    working_dir: /app
    environment:
      - PACT_BROKER_BASE_URL=${PACT_BROKER_BASE_URL}
      - PACT_BROKER_TOKEN=${PACT_BROKER_TOKEN}
      - VERSION=${VERSION}
      - BRANCH=${BRANCH}
    volumes:
      - ./:/app
    command: >
      /bin/sh -c "pactflow publish-provider-contract ${OAS_PATH}
      --provider ${PACTICIPANT} 
      --provider-app-version $${VERSION} 
      --branch $${BRANCH} 
      --content-type application/yaml 
      --verification-exit-code=${EXIT_CODE} 
      --verification-results ${REPORT_PATH} 
      --verification-results-content-type ${REPORT_FILE_CONTENT_TYPE}
      --verifier ${VERIFIER_TOOL}"